webtalk_init -webtalk_dir C:/Users/patre/FPGA/keyboardDecoder/keyboardDecoder.sim/sim_1/behav/xsim/xsim.dir/keyboard_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Apr 22 12:53:11 2019" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "a5827e10-3f04-4605-a88b-2bd1c5e51bdb" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "1d37c5b2392245a8aba407140568e5ce" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "23" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2592 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1001 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.26_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "13548_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1179264936 -regid "" -xml C:/Users/patre/FPGA/keyboardDecoder/keyboardDecoder.sim/sim_1/behav/xsim/xsim.dir/keyboard_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/patre/FPGA/keyboardDecoder/keyboardDecoder.sim/sim_1/behav/xsim/xsim.dir/keyboard_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/patre/FPGA/keyboardDecoder/keyboardDecoder.sim/sim_1/behav/xsim/xsim.dir/keyboard_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
