set_property PACKAGE_PIN W5 [get_ports clk]
	set_property IOSTANDARD LVCMOS33 [get_ports sysclk]
	create_clock -period 10.00 -waveform {0 5} [get_ports sysclk]
	
set_property PACKAGE_PIN R2 [get_ports holdenable]
	set_property IOSTANDARD LVCMOS33 [get_ports holdenable]
	
set_property PACKAGE_PIN V17 [get_ports syson]
	set_property IOSTANDARD LVCMOS33 [get_ports syson]
	
set_property PACKAGE_PIN W7 [get_ports {SSDcathode[0]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {SSDcathode[0]}]
set_property PACKAGE_PIN W6 [get_ports {SSDcathode[1]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {SSDcathode[1]}]
set_property PACKAGE_PIN U8 [get_ports {SSDcathode[2]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {SSDcathode[2]}]
set_property PACKAGE_PIN V8 [get_ports {SSDcathode[3]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {SSDcathode[3]}]
set_property PACKAGE_PIN U5 [get_ports {SSDcathode[4]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {SSDcathode[4]}]
set_property PACKAGE_PIN V5 [get_ports {SSDcathode[5]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {SSDcathode[5]}]
set_property PACKAGE_PIN U7 [get_ports {SSDcathode[6]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {SSDcathode[6]}]
	
set_property PACKAGE_PIN U2 [get_ports {SSDanode[0]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {SSDanode[0]}]
set_property PACKAGE_PIN U4 [get_ports {SSDanode[1]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {SSDanode[1]}]
set_property PACKAGE_PIN V4 [get_ports {SSDanode[2]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {SSDanode[2]}]
set_property PACKAGE_PIN W4 [get_ports {SSDanode[3]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {SSDanode[3]}]

set_property PACKAGE_PIN C17 [get_ports keyclk]
	set_property IOSTANDARD LVCMOS33 [get_ports keyclk]
	set_property PULLUP true [get_ports keyclk]
	
set_property PACKAGE_PIN B17 [get_ports keydata]
	set_property IOSTANDARD LVCMOS33 [get_ports keydata]
	set_property PULLUP true [get_ports keydata]
