set_property PACKAGE_PIN W5 [get_ports sysclk]
	set_property IOSTANDARD LVCMOS33 [get_ports sysclk]
	create_clock -period 10.00 -waveform {0 5} [get_ports sysclk]
	
set_property PACKAGE_PIN R2 [get_ports holdenable]
	set_property IOSTANDARD LVCMOS33 [get_ports holdenable]
	
set_property PACKAGE_PIN V17 [get_ports syson]
	set_property IOSTANDARD LVCMOS33 [get_ports syson]
	
set_property PACKAGE_PIN W7 [get_ports {SSDcathode[6]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {SSDcathode[6]}]
set_property PACKAGE_PIN W6 [get_ports {SSDcathode[5]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {SSDcathode[5]}]
set_property PACKAGE_PIN U8 [get_ports {SSDcathode[4]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {SSDcathode[4]}]
set_property PACKAGE_PIN V8 [get_ports {SSDcathode[3]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {SSDcathode[3]}]
set_property PACKAGE_PIN U5 [get_ports {SSDcathode[2]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {SSDcathode[2]}]
set_property PACKAGE_PIN V5 [get_ports {SSDcathode[1]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {SSDcathode[1]}]
set_property PACKAGE_PIN U7 [get_ports {SSDcathode[0]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {SSDcathode[0]}]
	
set_property PACKAGE_PIN U2 [get_ports {SSDanode[0]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {SSDanode[0]}]
set_property PACKAGE_PIN U4 [get_ports {SSDanode[1]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {SSDanode[1]}]
set_property PACKAGE_PIN V4 [get_ports {SSDanode[2]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {SSDanode[2]}]
set_property PACKAGE_PIN W4 [get_ports {SSDanode[3]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {SSDanode[3]}]

set_property PACKAGE_PIN C17 [get_ports keyclk]
	set_property IOSTANDARD LVCMOS33 [get_ports keyclk]
	set_property PULLUP true [get_ports keyclk]
	
set_property PACKAGE_PIN B17 [get_ports keydata]
	set_property IOSTANDARD LVCMOS33 [get_ports keydata]
	set_property PULLUP true [get_ports keydata]
	
set_property PACKAGE_PIN U16 [get_ports {sentenceled[0]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {sentenceled[0]}]
set_property PACKAGE_PIN E19 [get_ports {sentenceled[1]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {sentenceled[1]}]
set_property PACKAGE_PIN U19 [get_ports {sentenceled[2]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {sentenceled[2]}]
set_property PACKAGE_PIN V19 [get_ports {sentenceled[3]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {sentenceled[3]}]
	
set_property PACKAGE_PIN V13 [get_ports {wordled[0]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {wordled[0]}]
set_property PACKAGE_PIN V3 [get_ports {wordled[1]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {wordled[1]}]
set_property PACKAGE_PIN W3 [get_ports {wordled[2]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {wordled[2]}]
set_property PACKAGE_PIN U3 [get_ports {wordled[3]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {wordled[3]}]
set_property PACKAGE_PIN P3 [get_ports {wordled[4]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {wordled[4]}]
set_property PACKAGE_PIN N3 [get_ports {wordled[5]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {wordled[5]}]
set_property PACKAGE_PIN P1 [get_ports {wordled[6]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {wordled[6]}]
set_property PACKAGE_PIN L1 [get_ports {wordled[7]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {wordled[7]}]
	
set_property PACKAGE_PIN W18 [get_ports led]
	set_property IOSTANDARD LVCMOS33 [get_ports led]
	
#set_property PACKAGE_PIN T1 [get_ports {autoread]
	#set_property IOSTANDARD LVCMOS33 [get_ports {autoread]
	
set_property PACKAGE_PIN W16 [get_ports reset]
	set_property IOSTANDARD LVCMOS33 [get_ports reset]
	
set_property PACKAGE_PIN V16 [get_ports changemode]
	set_property IOSTANDARD LVCMOS33 [get_ports changemode]
	
set_property PACKAGE_PIN T18 [get_ports nextsen]
	set_property IOSTANDARD LVCMOS33 [get_ports nextsen]
set_property PACKAGE_PIN W19 [get_ports prevword]
	set_property IOSTANDARD LVCMOS33 [get_ports prevword]
set_property PACKAGE_PIN T17 [get_ports nextword]
	set_property IOSTANDARD LVCMOS33 [get_ports nextword]
set_property PACKAGE_PIN U17 [get_ports prevsen]
	set_property IOSTANDARD LVCMOS33 [get_ports prevsen]
	

